version: '3'

services:
  web:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "80:3000"
    volumes:
      - ~/dotorimarket/appstore/files:/app/files
    environment:
      - JWT_SECRET=yessecret
      - DB_DEFAULT_HOST=mongodb://db:27017/dotorimarket-appstore
  db:
    image: mongo:4.2.8
    ports:
      - "27017:27017"
    volumes:
      - ~/dotorimarket/appstore/db:/data/db