version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "80:3000"
      - "443:3000"
    volumes:
      - ~/dotorimarket/appstore/files:/app/files
    environment:
      - JWT_SECRET=yessecret
      - DB_DEFAULT_HOST=mongodb://dotori-user:Ehxhfl0706!%40@db:27017/dotorimarket-appstore?authSource=admin
    networks:
      - dotorimarket
  db:
    build: ./mongodb
    ports:
      - "27890:27017"
    volumes:
      - ~/dotorimarket/appstore/db:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongo-admin
      - MONGO_INITDB_ROOT_PASSWORD=Ahdrh0706!@
    networks:
      - dotorimarket

networks:
  dotorimarket:
